"""DocFlow synthetic-document corpus generator (manufacturing profile).

Deterministic: one (company, seed) -> identical content and identical PDF
bytes (reportlab invariant mode; no wall-clock reads, fixed base dates).
Guardrails (PLAN.md section 4): fictional people/vendors from fixed pools;
canonical fake PII only (SSN 000-00-0000, phones 555-01xx, @example.com);
incidents only at the fictional "Plant 7, Demoville"; no logos, company name
as plain text; every page gets the SYNTHETIC DEMO DATA watermark + footer.
Planted story (exact -- the demo script relies on it): warranty claims
WC-2214 (serial SN-44781) and WC-2231 fall OUTSIDE their coverage windows
(the other three inside); Line 3 defect rate drifts 1.2 -> 1.9 -> 3.1 -> 4.8
percent across the four inspections (other lines stable); invoice INV-88213
(Miller Tooling LLC, 2023-11-02) carries serial SN-44781 for the cross-check.
"""
from __future__ import annotations

import calendar
import json
import os
import random
import re
from datetime import date, timedelta
from xml.sax.saxutils import escape as _esc

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

__all__ = ["TAXONOMY", "ROUTING", "WATERMARK_TEXT", "FOOTER_TEXT", "generate_corpus"]

WATERMARK_TEXT = "SYNTHETIC DEMO DATA"
FOOTER_TEXT = "Synthetic demonstration document generated by DocFlow. Not a real record."
FICTIONAL_SITE = "Plant 7, Demoville"
_DEFAULT_SITE = FICTIONAL_SITE
FAKE_SSN = "000-00-0000"

# Fixed fictional pools -- never real people, companies, or sites.
PEOPLE = ["Dana Whitfield", "Marcus Chen", "Priya Natarajan", "Rosa Delgado", "Samuel Okafor",
          "Lena Vasquez", "Theo Brandt", "Aiko Tanaka", "Colin Marsh", "Farida Aziz"]
VENDORS = {"Miller Tooling LLC": "410 Foundry Rd, Demoville",
           "Vexler Steel Co": "88 Ingot Ave, Demoville",
           "Harlan Fastener Supply": "12 Dockside Ln, Demoville"}
VENDOR_NAMES = list(VENDORS)
_DEFAULT_VENDORS = dict(VENDORS)
CARRIERS = ["Demoville Freight Lines", "BlueRock Logistics"]
_DEFAULT_CARRIERS = list(CARRIERS)
DESTINATIONS = ["Fairview Distribution Center, Fairview", "Osborn Park Depot, Osborn Park"]
_DEFAULT_DESTINATIONS = list(DESTINATIONS)
# contract terms are world-settable; the two CT documents and the research
# call's suggested questions must agree, so they read from this one place
CONTRACT = {"supplier": "Miller Tooling LLC", "penalty_pct": "5", "cap_pct": "15",
            "warranty_months": "24", "filing_days": "30"}
PARTS = [("Hardened tool steel blank 4140, 2 in", 8640), ("Carbide end mill, 12 mm, 4-flute", 4275),
         ("CNC spindle bearing assembly", 21400), ("Hydraulic fitting kit, 3/8 in", 1890),
         ("Precision ground shaft, 25 mm", 12999), ("Weld filler wire ER70S-6, 33 lb spool", 5425),
         ("M8 hex fastener assortment, 500 ct", 1260), ("Conveyor belt section, 600 mm", 30150),
         ("Industrial gearbox oil, 5 gal", 7350), ("Pneumatic valve bank, 4-station", 16700)]

_DEFAULT_PARTS = list(PARTS)

# type -> corpus shape (count, doc-id prefix, printed title)
TAXONOMY = {
    "supplier_invoice":   {"count": 4, "prefix": "INV", "title": "Supplier Invoice"},
    "purchase_order":     {"count": 2, "prefix": "PO",  "title": "Purchase Order"},
    "warranty_claim":     {"count": 5, "prefix": "WC",  "title": "Warranty Claim"},
    "quality_inspection": {"count": 4, "prefix": "QIR", "title": "Quality Inspection Report"},
    "safety_incident":    {"count": 2, "prefix": "SI",  "title": "Safety Incident Report"},
    "hr_document":        {"count": 1, "prefix": "HR",  "title": "HR Document"},
    "shipping_manifest":  {"count": 1, "prefix": "SM",  "title": "Shipping Manifest"},
    "marketing":          {"count": 1, "prefix": "MKT", "title": "Marketing Mail"},
    "supplier_contract":  {"count": 4, "prefix": "CT",  "title": "Supplier Agreement"},
}
_DEFAULT_TITLES = {t: m["title"] for t, m in TAXONOMY.items()}

# PLAN.md routing matrix. Secure lanes extract only from a redacted copy;
# marketing routes to no lane (archive).
ROUTING = {
    "supplier_invoice":   {"extract": True,  "audit": False, "secure": False},
    "purchase_order":     {"extract": True,  "audit": False, "secure": False},
    "warranty_claim":     {"extract": True,  "audit": True,  "secure": False},
    "quality_inspection": {"extract": True,  "audit": True,  "secure": False},
    "safety_incident":    {"extract": True,  "audit": False, "secure": True},
    "hr_document":        {"extract": False, "audit": False, "secure": True},
    "shipping_manifest":  {"extract": True,  "audit": False, "secure": False},
    "marketing":          {"extract": False, "audit": False, "secure": False},
    "supplier_contract":  {"extract": False, "audit": False, "secure": False},
}

# claim_id, serial, purchase date, term months, failure date, cents, line, planted
# ---------------------------------------------------------------- LLM records
# The research call authors the actual document records for the customer's
# industry: what failed, when, for how much. The values below are only the
# fallback used when that call does not run, and the seed the test suite pins.
# Whatever the model writes, the app recomputes ground truth from it, so the
# arithmetic the demo proves is always the arithmetic on the page.
GEN = {"claims": [], "invoices": [], "inspections": []}


def _d(v, fallback):
    """A date the model wrote, or the fallback if it wrote nonsense."""
    try:
        y, m, d = str(v)[:10].split("-")
        return date(int(y), int(m), int(d))
    except Exception:
        return fallback


def _cents(v, fallback):
    try:
        n = float(re.sub(r"[^0-9.]", "", str(v)))
        return int(round(n * 100)) if n > 0 else fallback
    except Exception:
        return fallback


def _claims_spec(rng):
    """The claim records to render: the model's, repaired, or the default pack.

    A demo with nothing outside its warranty window has no money story, so if
    the model's claims are all in-window the two largest are pushed past their
    term. The repair is arithmetic on the model's own dates, never a made-up
    number, and every rendered document then agrees with the tables.
    """
    rows = []
    for i, c in enumerate(GEN.get("claims") or []):
        purchased = _d(c.get("purchase_date"), date(2024, 6, 1))
        try:
            term = max(6, min(60, int(re.sub(r"[^0-9]", "", str(c.get("warranty_term_months") or 24)))))
        except Exception:
            term = 24
        failed = _d(c.get("failure_date"), _add_months(purchased, term + 2))
        if failed <= purchased:
            failed = _add_months(purchased, term + 2)
        rows.append([str(c.get("claim_id") or f"WC-{2214 + i}")[:16],
                     str(c.get("unit_serial") or f"SN-{44781 + i * 137}")[:20],
                     purchased, term, failed,
                     _cents(c.get("claim_amount"), 120000 + i * 31000),
                     str(c.get("production_line") or f"Line {i % 4 + 1}")[:24],
                     False])
    # The corpus shape is a contract the pipeline and the pages rely on, so a
    # short or over-long model response is padded or trimmed rather than
    # allowed to change how many documents exist.
    want = len(WARRANTY_SPEC)
    if len(rows) < 2:
        return [list(x) for x in WARRANTY_SPEC]
    for i in range(len(rows), want):
        rows.append(list(WARRANTY_SPEC[i]))
    rows = rows[:want]
    outside = [r for r in rows if r[4] > _add_months(r[2], r[3])]
    if len(outside) < 2:
        for r in sorted(rows, key=lambda x: -x[5])[:2]:
            r[4] = _add_months(_add_months(r[2], r[3]), 2)
    rows[0][7] = True                       # the invoice cross-check anchors here
    return rows


WARRANTY_SPEC = [
    ("WC-2214", "SN-44781", date(2023, 11, 2), 24, date(2026, 3, 18), 214000, "Line 3", True),
    ("WC-2219", "SN-51209", date(2024, 9, 10), 24, date(2026, 2, 14), 68550, "Line 1", False),
    ("WC-2222", "SN-47332", date(2025, 1, 26), 18, date(2026, 4, 2), 142075, "Line 2", False),
    ("WC-2228", "SN-53867", date(2024, 12, 5), 36, date(2026, 5, 20), 31000, "Line 4", False),
    ("WC-2231", "SN-49118", date(2023, 8, 15), 24, date(2026, 1, 22), 117000, "Line 3", True),
]
CLAIM_PRODUCTS = {"WC-2214": "Servo actuator assembly", "WC-2219": "Spindle bearing cartridge",
                  "WC-2222": "Hydraulic manifold block", "WC-2228": "Line control module",
                  "WC-2231": "Drive coupling, 40 mm"}
FAILURE_NOTES = {
    "WC-2214": "Servo actuator seized at shift start; Line 3 halted 47 minutes until the spare "
               "unit was fitted.",
    "WC-2219": "Bearing noise above the acceptance limit during routine vibration check.",
    "WC-2222": "Persistent external leak at the manifold face; sealing surface out of flatness.",
    "WC-2228": "Intermittent fault codes and uncommanded stops; module swap cleared the fault.",
    "WC-2231": "Drive coupling sheared on the Line 3 infeed during normal load; no overload "
               "event on the drive log.",
}

# Narrative prose the research LLM may rewrite per industry. Keys map 1:1 to
# slots in the builders; defaults are the shipped manufacturing voice, so a
# failed research call still yields complete documents.
NARR = {
    "component_names": list(CLAIM_PRODUCTS.values()),
    "claim_failures": list(FAILURE_NOTES.values()),
    "claim_resolution": "Credit or replacement under the supplier warranty terms.",
    "inspection_method": "AQL sampling per QP-104, visual + gauge",
    "incident_areas": ["Line 3 guarding, west end", "Receiving dock, bay 2"],
    "incident_roles": ["Maintenance Mechanic", "Material Handler"],
    "incident_narratives": [
        "While adjusting the Line 3 infeed guard, the employee pinched the left index "
        "finger between the guard frame and its bracket. First aid on site; returned same shift.",
        "Employee slipped on hydraulic fluid residue near bay 2 while staging inbound "
        "pallets. Minor bruising only; area cordoned and cleaned."],
    "incident_actions": [
        "Guard adjustment procedure updated; two-person rule reinforced for guard work.",
        "Spill kit restocked at the dock; anti-slip floor coating scheduled."],
    "hr_from_title": "Quality Technician II",
    "hr_to_title": "Senior Quality Technician",
    "hr_note": "Promotion recognizes sustained inspection accuracy and audit "
               "leadership. Payroll change effective with the April cycle.",
    "marketing_headline": "SPRING 2026 ALLOY STOCK CATALOG",
    "marketing_body": "New season, sharper prices on the alloys your floor runs on. Vexler "
                      "Steel now stocks over 400 certified grades, same-week delivery.",
    "marketing_bullets": "- 4140 and 4340 pre-hardened bar, cut to length<br/>- Stainless plate "
                         "304/316 with mill certs<br/>- Volume pricing on orders over 5 tons",
    "contract_scope": "Supplier will manufacture and deliver the components listed in each "
                      "purchase order issued under this agreement.",
    "contract_warranty_procedure":
        "To return a defective component, Buyer requests a return authorisation "
        "number within ten business days of identifying the defect, quoting the "
        "purchase order number, the component serial number and the observed "
        "failure mode. Supplier issues the authorisation within two business "
        "days and bears inbound freight on authorised returns. Replacement "
        "components ship within five business days of Supplier receiving the "
        "defective unit, and carry the balance of the original warranty term or "
        "ninety days, whichever is longer.",
    "contract_claims_documentation":
        "Every reimbursement claim must include the unit serial number, the "
        "original delivery date, the failure date, a description of the failure "
        "mode written by the technician who observed it, and copies of the "
        "service records for the affected unit. Claims relying on third-party "
        "inspection reports must attach the full report, not a summary. "
        "Incomplete claims are returned once for completion; a claim returned a "
        "second time is closed and must be refiled.",
    "contract_service_levels":
        "Supplier maintains a technical support line staffed during Buyer's "
        "production hours, with a response target of four business hours for "
        "line-down events and one business day for all other enquiries. Twice "
        "yearly, Supplier's quality engineer and Buyer's supplier-quality lead "
        "review defect trends, open claims and corrective actions, and agree a "
        "written action list with owners and dates.",
    "contract_liability":
        "Neither party is liable to the other for loss of profit, loss of "
        "production or indirect loss, except where caused by wilful misconduct. "
        "Supplier's aggregate liability under this agreement is capped at the "
        "total value of purchase orders placed in the twelve months preceding "
        "the claim.",
    "claim_incident_narratives": [
        "Operators reported intermittent stalling on the affected station over "
        "two shifts before the unit failed outright at the start of the third. "
        "The line supervisor logged the first stall as a minor fault and "
        "cleared it by power-cycling; the second stall tripped the downstream "
        "accumulation sensor and forced a controlled stop. Maintenance replaced "
        "the unit from spares and returned the line to speed, tagging the "
        "failed unit for warranty evaluation and quarantining it in the "
        "returns cage.",
        "The failure was found during the morning start-up checklist rather "
        "than in production: the operator noted an abnormal reading during "
        "warm-up and escalated before running product. Maintenance confirmed "
        "the fault, pulled the unit, and completed the swap inside the "
        "scheduled changeover window, so no production time was lost. The "
        "failed unit was tagged, photographed and logged in the maintenance "
        "system the same day.",
        "The unit failed under full load mid-shift with no prior warning "
        "logged. The area team followed the stoppage procedure, isolated the "
        "station and switched production to the parallel line at reduced rate "
        "while maintenance completed diagnosis. Inspection of the failed unit "
        "showed damage consistent with internal wear rather than misuse, and "
        "the service history shows the unit inside its scheduled maintenance "
        "intervals throughout.",
    ],
    "claim_impacts": [
        "The stoppage cost forty-seven minutes of line time and required "
        "rescheduling one shipment; no product was scrapped.",
        "No production impact: the fault was caught before the line started "
        "and the swap fit inside planned downtime.",
        "Output ran at reduced rate for the remainder of the shift, and one "
        "order moved to the following day with customer agreement.",
    ],
    "inspection_findings": [
        "Sampling across all four lines found workmanship generally within "
        "specification, with the defect concentration on one line materially "
        "above its trailing average. The dominant defect modes were seating "
        "and alignment faults at a single station, consistent between shifts, "
        "which points at fixturing or incoming component variation rather "
        "than operator technique. Recommend a first-article check on the next "
        "three incoming lots and a fixture calibration before the next run.",
        "Defect rates on three of four lines held steady against the prior "
        "month. The outlier line shows a rising trend for the third "
        "consecutive report, and the failed units share a common supplier lot "
        "code. Recommend quarantining the remaining stock from that lot, "
        "notifying the supplier quality contact, and re-inspecting finished "
        "goods built from it before release.",
    ],
}
_DEFAULT_NARR = {k: (list(v) if isinstance(v, list) else v) for k, v in NARR.items()}


def _narr(key, i=None):
    v = NARR.get(key, _DEFAULT_NARR.get(key))
    if i is None:
        return v
    d = _DEFAULT_NARR[key]
    try:
        return (v[i] if i < len(v) and str(v[i]).strip() else d[i % len(d)])
    except Exception:
        return d[i % len(d)]


def _title(t):
    return TAXONOMY[t]["title"].upper()


# report id, inspection date, per-line defect rate percent (Line 3 drifts upward)
QIR_SCHEDULE = [
    ("QIR-0781", date(2026, 2, 10), {"Line 1": 0.9, "Line 2": 1.1, "Line 3": 1.2, "Line 4": 0.8}),
    ("QIR-0782", date(2026, 3, 10), {"Line 1": 0.8, "Line 2": 1.2, "Line 3": 1.9, "Line 4": 0.8}),
    ("QIR-0783", date(2026, 4, 10), {"Line 1": 0.9, "Line 2": 1.0, "Line 3": 3.1, "Line 4": 0.7}),
    ("QIR-0784", date(2026, 5, 12), {"Line 1": 0.8, "Line 2": 1.1, "Line 3": 4.8, "Line 4": 0.9}),
]
QIR_REMARKS = {
    "QIR-0781": "All lines within control limits. No action required.",
    "QIR-0782": "Line 3 defect rate above its trailing average; monitor at next audit.",
    "QIR-0783": "Line 3 reject volume elevated; infeed alignment suspected. Follow-up scheduled.",
    "QIR-0784": "Line 3 exceeds the 4.0% control limit. Escalated to process engineering.",
}

INK, GREY = colors.Color(0.106, 0.192, 0.224), colors.Color(0.42, 0.42, 0.42)
RULE, HEADBG = colors.Color(0.78, 0.78, 0.78), colors.Color(0.933, 0.925, 0.912)
WMARK = colors.Color(0.70, 0.33, 0.33, alpha=0.13)  # grey-red, semi-transparent
S_TITLE = ParagraphStyle("t", fontName="Helvetica-Bold", fontSize=15, leading=19, spaceAfter=2)
S_SUB = ParagraphStyle("s", fontName="Helvetica", fontSize=9, leading=12, textColor=GREY,
                       spaceAfter=10)
S_BODY = ParagraphStyle("b", fontName="Helvetica", fontSize=9.5, leading=13)
S_CELL = ParagraphStyle("c", fontName="Helvetica", fontSize=9, leading=11)
S_H2 = ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=10.5, leading=14, spaceAfter=4)

def _d2(cents: int) -> str:
    return f"{cents // 100}.{cents % 100:02d}"

def _usd(cents: int) -> str:
    return f"${cents // 100:,}.{cents % 100:02d}"

def _phone(rng: random.Random) -> str:
    return f"555-01{rng.randrange(100):02d}"  # canonical fictional exchange

def _email(name: str) -> str:
    return name.lower().replace(" ", ".") + "@example.com"

def _add_months(d: date, months: int) -> date:
    m = d.month - 1 + months
    y, m = d.year + m // 12, m % 12 + 1
    return date(y, m, min(d.day, calendar.monthrange(y, m)[1]))

def _invariant_canvas(*args, **kwargs) -> Canvas:
    kwargs["invariant"] = 1  # fixed CreationDate + doc ID -> byte-stable PDFs
    return Canvas(*args, **kwargs)

def _page_decorator(company: str):
    def draw(canv, _doc):
        w, h = LETTER
        canv.saveState()
        canv.setFont("Helvetica-Bold", 10)  # company name: plain text header only
        canv.setFillColor(INK)
        canv.drawString(0.75 * inch, h - 0.55 * inch, company)
        canv.setFont("Helvetica", 7.5)
        canv.setFillColor(GREY)
        canv.drawRightString(w - 0.75 * inch, h - 0.55 * inch,
                             f"Synthetic demo corpus - page {canv.getPageNumber()}")
        canv.setLineWidth(0.75)
        canv.setStrokeColor(RULE)
        canv.line(0.75 * inch, h - 0.63 * inch, w - 0.75 * inch, h - 0.63 * inch)
        # Watermark lives in the margin bands, not over the body: a giant center
        # overlay interleaves with table text when pages are machine-parsed.
        canv.setFont("Helvetica-Bold", 15)
        canv.setFillColor(WMARK)
        canv.drawCentredString(w / 2, h - 0.92 * inch, WATERMARK_TEXT)
        canv.drawCentredString(w / 2, 0.62 * inch, WATERMARK_TEXT)
        canv.restoreState()
        canv.saveState()
        canv.setFont("Helvetica-Oblique", 7.5)
        canv.setFillColor(GREY)
        canv.drawCentredString(w / 2, 0.45 * inch, FOOTER_TEXT)
        canv.restoreState()
    return draw

def _render(path: str, company: str, story: list) -> None:
    doc = SimpleDocTemplate(path, pagesize=LETTER, leftMargin=0.75 * inch,
                            rightMargin=0.75 * inch, topMargin=1.0 * inch,
                            bottomMargin=0.85 * inch, title=os.path.basename(path)[:-4],
                            author="DocFlow synthetic corpus generator")
    deco = _page_decorator(company)
    doc.build(story, onFirstPage=deco, onLaterPages=deco, canvasmaker=_invariant_canvas)

def _table(data, widths, styles, **kw) -> Table:
    t = Table(data, colWidths=widths, **kw)
    t.setStyle(TableStyle(styles + [("TOPPADDING", (0, 0), (-1, -1), 3),
                                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
    return t

def _kv(pairs) -> Table:
    rows = [[Paragraph(f"<b>{_esc(str(k))}</b>", S_CELL), Paragraph(_esc(str(v)), S_CELL)]
            for k, v in pairs]
    return _table(rows, [1.9 * inch, 4.6 * inch],
                  [("VALIGN", (0, 0), (-1, -1), "TOP"),
                   ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.Color(0.87, 0.87, 0.87))])

def _grid(header, rows, widths) -> Table:
    return _table([header] + rows, widths,
                  [("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8.5),
                   ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
                   ("BACKGROUND", (0, 0), (-1, 0), HEADBG),
                   ("GRID", (0, 0), (-1, -1), 0.4, RULE),
                   ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                   ("VALIGN", (0, 0), (-1, -1), "TOP")], repeatRows=1)

def _items_grid(items) -> Table:
    return _grid(["Description", "Qty", "Unit price", "Amount"],
                 [[Paragraph(_esc(d), S_CELL), str(q), _usd(p), _usd(q * p)] for d, q, p in items],
                 [3.9 * inch, 0.7 * inch, 1.2 * inch, 1.2 * inch])

def _totals(rows) -> Table:
    return _table([[label, _usd(c)] for label, c in rows], [1.7 * inch, 1.3 * inch],
                  [("FONT", (0, 0), (-1, -1), "Helvetica", 9),
                   ("FONT", (0, -1), (-1, -1), "Helvetica-Bold", 9.5),
                   ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                   ("LINEABOVE", (0, -1), (-1, -1), 0.8, INK)], hAlign="RIGHT")

def _items_gt(items):
    return [{"description": d, "qty": q, "unit_price": _d2(p), "amount": _d2(q * p)}
            for d, q, p in items]

def _form(title, subtitle, pairs, *tail):
    """Story skeleton shared by every form-style document."""
    return [Paragraph(title, S_TITLE), Paragraph(subtitle, S_SUB), _kv(pairs), *tail]

def _sec(heading, body):
    return [Spacer(0, 10), Paragraph(heading, S_H2), Paragraph(_esc(body), S_BODY)]

def _invoice(inv_id, company, vendor, inv_date, items, contact, phone, planted):
    subtotal = sum(q * p for _, q, p in items)
    tax = (subtotal * 825 + 5000) // 10000  # 8.25 percent, half-up, exact cents
    total, due = subtotal + tax, inv_date + timedelta(days=30)
    story = _form("INVOICE", f"{_esc(vendor)} - {_esc(VENDORS.get(vendor, '1 Industrial Way, Demoville'))}",
                  [("Invoice number", inv_id), ("Invoice date", inv_date.isoformat()),
                   ("Payment due", due.isoformat()), ("Terms", "Net 30"),
                   ("Bill to", f"{company}, Receiving Dept, {FICTIONAL_SITE}"),
                   ("Vendor contact", f"{contact} - {_email(contact)} - {phone}")],
                  Spacer(0, 14), _items_grid(items), Spacer(0, 8),
                  _totals([("Subtotal", subtotal), ("Tax (8.25%)", tax), ("Total due", total)]))
    gt = {"invoice_number": inv_id, "vendor": vendor, "invoice_date": inv_date.isoformat(),
          "due_date": due.isoformat(), "subtotal": _d2(subtotal), "tax": _d2(tax),
          "total": _d2(total), "line_items": _items_gt(items),
          "serial_numbers": sorted({s for d, _, _ in items for s in re.findall(r"SN-\d+", d)})}
    return inv_id, story, gt, planted

def _build_invoices(company, rng):
    # The first invoice is the cross-check for claim one: same serial, same
    # purchase date, so "prove it" has an answer on another page.
    claims = _claims_spec(rng)
    anchor = claims[0]
    gen0 = (GEN.get("claims") or [{}])[0] if GEN.get("claims") else {}
    comp = (gen0.get("component") or _narr("component_names", 0))
    planted_items = [(f"{comp}, serial {anchor[1]}", 1, max(1000, anchor[5] - 40000)),
                     (f"{comp} mounting kit", 2, 4550),
                     ("On-site commissioning service, 1 day", 1, 35000)]
    inv_id = str((GEN.get("invoices") or [{}])[0].get("invoice_no") or "INV-88213")[:16] \
        if GEN.get("invoices") else "INV-88213"
    docs = [_invoice(inv_id, company, CONTRACT["supplier"], anchor[2],
                     planted_items, rng.choice(PEOPLE), _phone(rng), True)]
    extra = (GEN.get("invoices") or [])[1:4]
    for i in range(3):
        spec_i = extra[i] if i < len(extra) else {}
        vendor = str(spec_i.get("vendor") or rng.choice(VENDOR_NAMES))[:60]
        inv_date = date(2026, 4, 6) + timedelta(days=rng.randrange(70))
        items = [(d, rng.randint(1, 12), p) for d, p in rng.sample(PARTS, rng.randint(3, 5))]
        docs.append(_invoice(f"INV-{88214 + i}", company, vendor, inv_date, items,
                             rng.choice(PEOPLE), _phone(rng), False))
    return docs

def _build_pos(company, rng):
    docs = []
    for i, po_id in enumerate(["PO-3341", "PO-3342"]):
        vendor, od = VENDOR_NAMES[i % 3], date(2026, 3, 9) + timedelta(days=rng.randrange(80))
        need, buyer = od + timedelta(days=21), rng.choice(PEOPLE)
        items = [(d, rng.randint(2, 20), p) for d, p in rng.sample(PARTS, rng.randint(3, 4))]
        total = sum(q * p for _, q, p in items)
        story = _form("PURCHASE ORDER", f"{_esc(company)} - Procurement",
                      [("PO number", po_id), ("Order date", od.isoformat()),
                       ("Need-by date", need.isoformat()),
                       ("Vendor", f"{vendor}, {VENDORS.get(vendor, '1 Industrial Way, Demoville')}"),
                       ("Ship to", f"{company}, {FICTIONAL_SITE}"),
                       ("Buyer", f"{buyer} - {_email(buyer)} - {_phone(rng)}")],
                      Spacer(0, 14), _items_grid(items), Spacer(0, 8),
                      _totals([("PO total", total)]))
        gt = {"po_number": po_id, "vendor": vendor, "order_date": od.isoformat(),
              "need_by_date": need.isoformat(), "total": _d2(total),
              "line_items": _items_gt(items)}
        docs.append((po_id, story, gt, False))
    return docs

def _build_claims(company, rng):
    docs = []
    for k, (cid, serial, purchased, term, failed, cents, line, planted) in enumerate(_claims_spec(rng)):
        expires, contact = _add_months(purchased, term), rng.choice(PEOPLE)
        proof = f"Invoice INV-88213, {CONTRACT['supplier']}" if cid == "WC-2214" else "On file"
        gen = (GEN.get("claims") or [])
        component = ((gen[k].get("component") if k < len(gen) else "") or "").strip() \
            or _narr("component_names", k)
        failure_note = ((gen[k].get("failure_note") if k < len(gen) else "") or "").strip() \
            or _narr("claim_failures", k)
        story = (_form(_title("warranty_claim"),
                       f"Supplier warranty recovery claim submitted by {_esc(company)}",
                       [("Claim ID", cid), ("Claimant", f"{company}, {FICTIONAL_SITE}"),
                        ("Component", component), ("Serial number", serial),
                        ("Purchase date", purchased.isoformat()), ("Warranty term", f"{term} months"),
                        ("Failure date", failed.isoformat()), ("Claim amount", _usd(cents)),
                        ("Production line", line), ("Proof of purchase", proof),
                        ("Filed by", f"{contact} - {_email(contact)} - {_phone(rng)}")])
                 + _sec("Failure description", failure_note)
                 + _sec("Incident narrative", _narr("claim_incident_narratives", k))
                 + _sec("Operational impact", _narr("claim_impacts", k))
                 + _sec("Requested resolution", _narr("claim_resolution")))
        gt = {"claim_id": cid, "serial_number": serial, "component": component,
              "purchase_date": purchased.isoformat(), "warranty_term_months": term,
              "failure_date": failed.isoformat(), "warranty_expires": expires.isoformat(),
              "within_warranty": failed <= expires, "claim_amount": _d2(cents),
              "production_line": line,
              "proof_of_purchase": "INV-88213" if cid == "WC-2214" else None}
        docs.append((cid, story, gt, planted))
    return docs

def _build_qirs(company, rng):
    docs, shifts = [], ["First shift", "Second shift", "First shift", "First shift"]
    for i, (qid, d, rates) in enumerate(QIR_SCHEDULE):
        inspector, rows, gt_rows, tu, td = rng.choice(PEOPLE), [], [], 0, 0
        for line, rate in rates.items():
            units = rng.choice([1000, 2000, 3000])
            defects = int(round(rate * units / 100))  # rates chosen so this is exact
            tu, td = tu + units, td + defects
            rows.append([line, f"{units:,}", str(defects), f"{rate:.1f}%"])
            gt_rows.append({"line": line, "units_inspected": units, "defects": defects,
                            "defect_rate_pct": rate})
        rows.append(["All lines", f"{tu:,}", str(td), f"{td / tu * 100:.2f}%"])
        findings = _narr("inspection_findings", i)
        story = (_form(_title("quality_inspection"),
                       f"Final assembly audit - {_esc(company)}, {FICTIONAL_SITE}",
                       [("Report ID", qid), ("Inspection date", d.isoformat()),
                        ("Shift", shifts[i]), ("Inspector", f"{inspector} - {_email(inspector)}"),
                        ("Method", _narr("inspection_method"))],
                       Spacer(0, 14),
                       _grid(["Production line", "Units inspected", "Defects", "Defect rate"],
                             rows, [1.9 * inch, 1.8 * inch, 1.5 * inch, 1.8 * inch]))
                 + _sec("Inspector remarks", QIR_REMARKS[qid])
                 + _sec("Inspector's findings", findings))
        gt = {"report_id": qid, "inspection_date": d.isoformat(), "inspector": inspector,
              "lines": gt_rows, "line3_defect_rate_pct": rates["Line 3"]}
        docs.append((qid, story, gt, True))
    return docs

def _build_incidents(company, rng):
    specs = [("SI-0112", date(2026, 4, 21), "09:40"),
             ("SI-0113", date(2026, 5, 30), "14:15")]
    docs = []
    for k, (sid, d, t) in enumerate(specs):
        area, role = _narr("incident_areas", k), _narr("incident_roles", k)
        narrative, action = _narr("incident_narratives", k), _narr("incident_actions", k)
        employee, reporter = rng.sample(PEOPLE, 2)
        story = (_form(_title("safety_incident"), f"Internal EHS record - {_esc(company)}",
                       [("Incident ID", sid), ("Date", d.isoformat()), ("Time", t),
                        ("Site", FICTIONAL_SITE), ("Area", area), ("Employee", f"{employee} ({role})"),
                        ("Reported by", f"{reporter} - {_email(reporter)} - {_phone(rng)}"),
                        ("Injury classification", "First aid only"), ("OSHA recordable", "No"),
                        ("Days away from work", "0")])
                 + _sec("What happened", narrative) + _sec("Corrective action", action))
        gt = {"incident_id": sid, "incident_date": d.isoformat(), "site": FICTIONAL_SITE,
              "area": area, "employee": employee, "severity": "First aid only",
              "osha_recordable": False}
        docs.append((sid, story, gt, False))
    return docs

def _build_hr(company, rng):
    employee, approver = "Dana Whitfield", rng.choice(PEOPLE[1:])
    story = (_form(_title("hr_document"),
                   f"Human Resources - {_esc(company)} - CONFIDENTIAL",
                   [("Document ID", "HR-0007"), ("Employee", employee),
                    ("Employee ID", "EMP-0042"), ("SSN", FAKE_SSN),
                    ("Contact", f"{_email(employee)} - {_phone(rng)}"),
                    ("Work site", FICTIONAL_SITE), ("Effective date", "2026-04-01"),
                    ("Change", "Promotion"), ("From title", _narr("hr_from_title")),
                    ("To title", _narr("hr_to_title")), ("New annual salary", "$68,400.00"),
                    ("Approved by", approver)])
             + _sec("Notes", _narr("hr_note")))
    gt = {"document_id": "HR-0007", "document_type": "Employee status change",
          "employee": employee, "ssn": FAKE_SSN, "effective_date": "2026-04-01",
          "new_title": "Senior Quality Technician"}
    return [("HR-0007", story, gt, False)]

def _build_manifests(company, rng):
    docs = []
    for i, (mid, ship) in enumerate([("SM-0451", date(2026, 5, 14))]):
        carrier, dest = rng.choice(CARRIERS), DESTINATIONS[i]
        rows, gt_rows, tc, tw = [], [], 0, 0
        for j, (desc, _) in enumerate(rng.sample(PARTS, rng.randint(3, 4))):
            pkg, cartons, wt = f"{mid}-P{j + 1:02d}", rng.randint(1, 10), rng.randint(60, 400)
            tc, tw = tc + cartons, tw + wt
            rows.append([pkg, Paragraph(_esc(desc), S_CELL), str(cartons), f"{wt} lb"])
            gt_rows.append({"package_id": pkg, "contents": desc, "cartons": cartons,
                            "weight_lb": wt})
        rows.append(["Total", "", str(tc), f"{tw} lb"])
        seal = f"TRL-{rng.randrange(1000, 9999)} / SEAL-{rng.randrange(10000, 99999)}"
        story = _form("SHIPPING MANIFEST", f"Outbound freight - {_esc(company)}",
                      [("Manifest ID", mid), ("Ship date", ship.isoformat()),
                       ("Carrier", carrier), ("Origin", f"{company}, {FICTIONAL_SITE}"),
                       ("Destination", dest), ("Trailer / seal", seal)],
                      Spacer(0, 14),
                      _grid(["Package", Paragraph("<b>Contents</b>", S_CELL), "Cartons", "Weight"],
                            rows, [1.3 * inch, 3.6 * inch, 0.9 * inch, 1.2 * inch]))
        gt = {"manifest_id": mid, "ship_date": ship.isoformat(), "carrier": carrier,
              "origin": FICTIONAL_SITE, "destination": dest, "package_count": len(gt_rows),
              "total_cartons": tc, "total_weight_lb": tw, "packages": gt_rows}
        docs.append((mid, story, gt, False))
    return docs

def _build_marketing(company, rng):
    del company, rng  # junk mail is vendor-authored; nothing random needed
    # sender + copy come from the world so the junk reads native to the industry
    sender = VENDOR_NAMES[-1] if VENDOR_NAMES else "Vexler Steel Co"
    story = [Paragraph(_esc(_narr("marketing_headline")).upper(), S_TITLE),
             Paragraph(f"{_esc(sender)} - 88 Ingot Ave, Demoville", S_SUB),
             Paragraph(_esc(_narr("marketing_body")), S_BODY),
             Spacer(0, 8),
             Paragraph(_narr("marketing_bullets"), S_BODY),
             Spacer(0, 10), Paragraph("Request the catalog: sales@example.com - 555-0100 - "
                                      "www.example.com/catalog", S_BODY)]
    gt = {"title": _narr("marketing_headline"), "sender": sender,
          "contact_email": "sales@example.com"}
    return [("MKT-001", story, gt, False)]

def _build_contracts(company, rng):
    del rng  # contract terms are the story; nothing random belongs in them
    c = _esc(company)
    K = CONTRACT
    msa = [Paragraph("MASTER SUPPLY AGREEMENT", S_TITLE),
           Paragraph(f"CT-7701 - between {c} (Buyer) and {_esc(K['supplier'])} (Supplier) - "
                     f"effective 1 March 2024", S_SUB),
           Spacer(0, 8),
           Paragraph("1. Scope", S_H2),
           Paragraph(f"{_esc(_narr('contract_scope'))} Each purchase order "
                     f"references these terms unless it states otherwise in writing.", S_BODY),
           Spacer(0, 6),
           Paragraph("2. Delivery and late-delivery penalty", S_H2),
           Paragraph(f"Time is of the essence. Where delivery arrives after the need-by date "
                     f"on the purchase order, Buyer may deduct a late-delivery penalty of "
                     f"{K['penalty_pct']} percent ({K['penalty_pct']}%) of the purchase order "
                     f"value for each full week of delay, capped at {K['cap_pct']} percent "
                     f"({K['cap_pct']}%) in aggregate. Penalties are deducted from the next "
                     f"invoice, not invoiced separately.", S_BODY),
           Spacer(0, 6),
           Paragraph("3. Component warranty pass-through", S_H2),
           Paragraph(f"Supplier warrants all delivered components for {K['warranty_months']} "
                     f"months from delivery. Where Buyer honours an end-customer warranty "
                     f"claim caused by a defective supplied component, Supplier reimburses "
                     f"Buyer the component cost plus documented labour, provided the claim "
                     f"is notified within sixty (60) days of Buyer settling it.", S_BODY),
           Spacer(0, 6),
           Paragraph("4. Termination", S_H2),
           Paragraph("Either party may terminate on ninety (90) days written notice. "
                     "Purchase orders accepted before notice survive termination.", S_BODY),
           Spacer(0, 6),
           Paragraph("5. Warranty and returns procedure", S_H2),
           Paragraph(_esc(_narr("contract_warranty_procedure")), S_BODY),
           Spacer(0, 6),
           Paragraph("6. Claim documentation requirements", S_H2),
           Paragraph(_esc(_narr("contract_claims_documentation")), S_BODY),
           Spacer(0, 6),
           Paragraph("7. Service levels and quality reviews", S_H2),
           Paragraph(_esc(_narr("contract_service_levels")), S_BODY),
           Spacer(0, 6),
           Paragraph("8. Limitation of liability", S_H2),
           Paragraph(_esc(_narr("contract_liability")), S_BODY),
           Spacer(0, 6),
           Paragraph("9. Governing terms", S_H2),
           Paragraph("This agreement is governed by the laws of the State of Demoland. "
                     "It is fictional demonstration material and binds nobody.", S_BODY)]
    gt_msa = {"contract_id": "CT-7701", "supplier": K["supplier"],
              "late_delivery_penalty":
                  f"{K['penalty_pct']}% per full week, capped at {K['cap_pct']}%",
              "component_warranty_months": K["warranty_months"]}
    pol = [Paragraph("WARRANTY TERMS AND SERVICE POLICY", S_TITLE),
           Paragraph(f"CT-7702 - {c} - customer-facing policy - revision C, "
                     f"January 2025", S_SUB),
           Spacer(0, 8),
           Paragraph("1. Coverage window", S_H2),
           Paragraph(f"{c} warrants each unit against defects in materials and workmanship "
                     "for the warranty term stated on the unit's certificate, measured from "
                     "the date of purchase. Coverage ends when that term lapses; failures "
                     "reported after the coverage window are not eligible for repair or "
                     "replacement at company cost, and are quoted as billable service.", S_BODY),
           Spacer(0, 6),
           Paragraph("2. Filing a claim", S_H2),
           Paragraph(f"Claims must be filed within {K['filing_days']} days of the failure "
                     f"date, with the unit serial number, purchase date and a description of "
                     f"the failure mode. Claims missing a verifiable purchase date are held "
                     f"for review rather than denied outright.", S_BODY),
           Spacer(0, 6),
           Paragraph("3. Exclusions", S_H2),
           Paragraph("Damage from improper installation, unauthorised modification, or "
                     "operation outside the published duty cycle is excluded. Consequential "
                     "and incidental damages are excluded to the extent law allows.", S_BODY),
           Spacer(0, 6),
           Paragraph("4. Out-of-window goodwill", S_H2),
           Paragraph("Requests outside the coverage window may be considered for partial "
                     "goodwill credit where the failure mode matches an open quality "
                     "investigation. Goodwill is discretionary and never an admission "
                     "of liability.", S_BODY)]
    gt_pol = {"contract_id": "CT-7702", "policy": "Warranty Terms and Service Policy",
              "claim_filing_deadline_days": K["filing_days"]}
    # Two more contracts so the assistant's folder never rides on a single
    # classification: an SLA addendum and a liability rider, both written from
    # the same world narratives the assistant cites.
    v2 = VENDOR_NAMES[1 % len(VENDOR_NAMES)]
    sla = [Paragraph("SERVICE LEVEL ADDENDUM", S_TITLE),
           Paragraph(f"CT-7703 - addendum to the master agreement between {c} (Buyer) "
                     f"and {_esc(v2)} (Supplier) - effective March 2025", S_SUB),
           Spacer(0, 8),
           Paragraph("1. Service levels", S_H2),
           Paragraph(_esc(_narr("contract_service_levels")), S_BODY),
           Spacer(0, 6),
           Paragraph("2. Remedies", S_H2),
           Paragraph(f"Failure to meet a committed service level for two consecutive "
                     f"months entitles Buyer to the remedies of the master agreement, "
                     f"including the late-delivery credit of {K['penalty_pct']}% per full "
                     f"week, capped at {K['cap_pct']}% of the affected order.", S_BODY),
           Spacer(0, 6),
           Paragraph("3. Reporting", S_H2),
           Paragraph("Supplier delivers a monthly service report covering fill rate, "
                     "on-time delivery and open corrective actions. Reports are due the "
                     "fifth business day and are reviewed at the quarterly business "
                     "review. This is fictional demonstration material.", S_BODY)]
    gt_sla = {"contract_id": "CT-7703", "supplier": v2,
              "late_delivery_penalty": f"{K['penalty_pct']}% per full week"}
    rider = [Paragraph("LIABILITY AND INDEMNITY RIDER", S_TITLE),
             Paragraph(f"CT-7704 - rider to the master agreement - {c} - "
                       f"revision A, April 2025", S_SUB),
             Spacer(0, 8),
             Paragraph("1. Allocation of liability", S_H2),
             Paragraph(_esc(_narr("contract_liability")), S_BODY),
             Spacer(0, 6),
             Paragraph("2. Warranty interaction", S_H2),
             Paragraph(f"Nothing in this rider extends the component warranty of "
                       f"{K['warranty_months']} months or the claim filing deadline of "
                       f"{K['filing_days']} days; remedies for covered failures remain "
                       f"repair, replacement or credit at Supplier's election.", S_BODY),
             Spacer(0, 6),
             Paragraph("3. Survival", S_H2),
             Paragraph("Obligations under this rider survive termination for two years. "
                       "This is fictional demonstration material and binds nobody.", S_BODY)]
    gt_rider = {"contract_id": "CT-7704", "policy": "Liability and Indemnity Rider"}
    return [("CT-7701", msa, gt_msa, False), ("CT-7702", pol, gt_pol, False),
            ("CT-7703", sla, gt_sla, False), ("CT-7704", rider, gt_rider, False)]

def apply_world(world: dict | None) -> dict:
    """Reskin the corpus content from the research call's world spec.

    The LLM decides names and language — vendors, line items, sites, carriers,
    document titles, failure modes, contract terms — so an insurance run reads
    like insurance and a hospital run like a hospital. The generator keeps the
    arithmetic: ids, dates, amounts and the planted story stay under its
    control so the audit findings and money figures remain provable. Returns
    the applied values (defaults where the spec is silent) for the manifest.
    """
    global VENDORS, VENDOR_NAMES, PARTS, FICTIONAL_SITE, CARRIERS, DESTINATIONS
    # The model does not always honor the schema: any field can arrive as
    # prose, a list, or a JSON string. Wrong shapes fall back to defaults —
    # a live run died on contract arriving as a sentence and .get() on it.
    def _dic(x):
        return x if isinstance(x, dict) else {}
    def _lst(x):
        if isinstance(x, list):
            return x
        if isinstance(x, str) and x.strip():
            return [x]
        return []
    w = _dic(world)
    def strs(key, n, default):
        v = [str(x).strip()[:80] for x in _lst(w.get(key)) if str(x).strip()]
        return (v + default)[:max(n, len(v))] if v else default
    vendors = strs("vendors", 3, list(_DEFAULT_VENDORS))
    addresses = list(_DEFAULT_VENDORS.values())
    VENDORS = {v: addresses[i % len(addresses)] for i, v in enumerate(vendors)}
    VENDOR_NAMES = list(VENDORS)
    prices = [pr for _, pr in _DEFAULT_PARTS]
    items = strs("line_items", 4, [d for d, _ in _DEFAULT_PARTS])
    PARTS = [(d, prices[i % len(prices)]) for i, d in enumerate(items)]
    FICTIONAL_SITE = str(w.get("site") or _DEFAULT_SITE)[:80]
    CARRIERS = strs("carriers", 2, list(_DEFAULT_CARRIERS))
    DESTINATIONS = strs("destinations", 2, list(_DEFAULT_DESTINATIONS))
    labels = _dic(w.get("type_labels"))
    for t, meta in TAXONOMY.items():
        meta["title"] = str(labels.get(t) or _DEFAULT_TITLES[t])[:48]
    g = _dic(w.get("generated"))
    GEN["claims"] = [x for x in _lst(g.get("claims")) if isinstance(x, dict)][:6]
    GEN["invoices"] = [x for x in _lst(g.get("invoices")) if isinstance(x, dict)][:5]
    n = _dic(w.get("narratives"))
    for k, dflt in _DEFAULT_NARR.items():
        v = n.get(k)
        # Long-form prose is the point of the assistant lane: cap generously,
        # not at a tweet.
        cap = 1400
        if isinstance(dflt, list):
            vv = [str(x).strip()[:cap] for x in _lst(v)
                  if isinstance(x, str) and str(x).strip()]
            NARR[k] = vv if vv else list(dflt)
        else:
            if not isinstance(v, str):
                v = next((x for x in _lst(v) if isinstance(x, str)), None)
            NARR[k] = (v.strip()[:cap] or dflt) if v else dflt
    c = _dic(w.get("contract"))
    CONTRACT.update({
        "supplier": str(c.get("supplier") or VENDOR_NAMES[0])[:60],
        "penalty_pct": str(c.get("penalty_pct") or "5"),
        "cap_pct": str(c.get("cap_pct") or "15"),
        "warranty_months": str(c.get("warranty_months") or "24"),
        "filing_days": str(c.get("filing_days") or "30"),
    })
    return {"vendors": VENDOR_NAMES, "site": FICTIONAL_SITE,
            "titles": {t: m["title"] for t, m in TAXONOMY.items()},
            "contract": dict(CONTRACT)}


def generate_corpus(company: str, out_dir: str, seed: int = 38,
                    world: dict | None = None) -> dict:
    """Generate the 24-document corpus into out_dir and return the manifest:
    {"company", "seed", "generated": [{doc_id, type, filename, planted_trap,
    ground_truth}]} -- ground_truth carries the exact field values the
    certification gate verifies extraction against. Also written to
    {out_dir}/manifest.json."""
    rng = random.Random(seed)
    applied = apply_world(world)
    os.makedirs(out_dir, exist_ok=True)
    builders = (_build_invoices, _build_pos, _build_claims, _build_qirs,
                _build_incidents, _build_hr, _build_manifests, _build_marketing,
                _build_contracts)
    generated = []
    for dtype, build in zip(TAXONOMY, builders):  # TAXONOMY declaration order
        for doc_id, story, gt, planted in build(company, rng):
            filename = f"{doc_id}.pdf"
            _render(os.path.join(out_dir, filename), company, story)
            generated.append({"doc_id": doc_id, "type": dtype, "filename": filename,
                              "planted_trap": planted, "ground_truth": gt})
    counts = {t: sum(1 for e in generated if e["type"] == t) for t in TAXONOMY}
    if len(generated) != 24 or any(counts[t] != TAXONOMY[t]["count"] for t in TAXONOMY):
        raise RuntimeError(f"corpus shape mismatch: {counts}")
    manifest = {"company": company, "seed": seed, "generated": generated,
                "world": applied}
    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
    return manifest

if __name__ == "__main__":
    import sys
    _company = sys.argv[1] if len(sys.argv) > 1 else "Acme Manufacturing"
    _dest = sys.argv[2] if len(sys.argv) > 2 else "./corpus_out"
    print(f"wrote {len(generate_corpus(_company, _dest)['generated'])} documents to {_dest}")
