"""DocFlow synthetic-document corpus generator (manufacturing profile).

Deterministic: one (company, seed) -> identical content and identical PDF
bytes (reportlab invariant mode; no wall-clock reads, fixed base dates).
Guardrails (PLAN.md section 4): fictional people/vendors from fixed pools;
canonical fake PII only (SSN 000-00-0000, phones 555-01xx, @example.com);
incidents only at the fictional "Plant 7, Demoville"; no logos, company name
as plain text; every page gets the SYNTHETIC DEMO DATA watermark + footer.
Planted story (exact -- the demo script relies on it): warranty claims
WC-2214 (serial SN-44781) and WC-2231 fall OUTSIDE their coverage windows
(the other three inside); Line 3 defect rate drifts 1.2 -> 1.9 -> 3.1 -> 4.8
percent across the four inspections (other lines stable); invoice INV-88213
(Miller Tooling LLC, 2023-11-02) carries serial SN-44781 for the cross-check.
"""
from __future__ import annotations

import calendar
import json
import os
import random
import re
from datetime import date, timedelta
from xml.sax.saxutils import escape as _esc

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

__all__ = ["TAXONOMY", "ROUTING", "WATERMARK_TEXT", "FOOTER_TEXT", "generate_corpus"]

WATERMARK_TEXT = "SYNTHETIC DEMO DATA"
FOOTER_TEXT = "Synthetic demonstration document generated by DocFlow. Not a real record."
FICTIONAL_SITE = "Plant 7, Demoville"
FAKE_SSN = "000-00-0000"

# Fixed fictional pools -- never real people, companies, or sites.
PEOPLE = ["Dana Whitfield", "Marcus Chen", "Priya Natarajan", "Rosa Delgado", "Samuel Okafor",
          "Lena Vasquez", "Theo Brandt", "Aiko Tanaka", "Colin Marsh", "Farida Aziz"]
VENDORS = {"Miller Tooling LLC": "410 Foundry Rd, Demoville",
           "Vexler Steel Co": "88 Ingot Ave, Demoville",
           "Harlan Fastener Supply": "12 Dockside Ln, Demoville"}
VENDOR_NAMES = list(VENDORS)
CARRIERS = ["Demoville Freight Lines", "BlueRock Logistics"]
DESTINATIONS = ["Fairview Distribution Center, Fairview", "Osborn Park Depot, Osborn Park"]
PARTS = [("Hardened tool steel blank 4140, 2 in", 8640), ("Carbide end mill, 12 mm, 4-flute", 4275),
         ("CNC spindle bearing assembly", 21400), ("Hydraulic fitting kit, 3/8 in", 1890),
         ("Precision ground shaft, 25 mm", 12999), ("Weld filler wire ER70S-6, 33 lb spool", 5425),
         ("M8 hex fastener assortment, 500 ct", 1260), ("Conveyor belt section, 600 mm", 30150),
         ("Industrial gearbox oil, 5 gal", 7350), ("Pneumatic valve bank, 4-station", 16700)]

# type -> corpus shape (count, doc-id prefix, printed title)
TAXONOMY = {
    "supplier_invoice":   {"count": 5, "prefix": "INV", "title": "Supplier Invoice"},
    "purchase_order":     {"count": 2, "prefix": "PO",  "title": "Purchase Order"},
    "warranty_claim":     {"count": 5, "prefix": "WC",  "title": "Warranty Claim"},
    "quality_inspection": {"count": 4, "prefix": "QIR", "title": "Quality Inspection Report"},
    "safety_incident":    {"count": 2, "prefix": "SI",  "title": "Safety Incident Report"},
    "hr_document":        {"count": 1, "prefix": "HR",  "title": "HR Document"},
    "shipping_manifest":  {"count": 2, "prefix": "SM",  "title": "Shipping Manifest"},
    "marketing":          {"count": 1, "prefix": "MKT", "title": "Marketing Mail"},
    "supplier_contract":  {"count": 2, "prefix": "CT",  "title": "Supplier Agreement"},
}

# PLAN.md routing matrix. Secure lanes extract only from a redacted copy;
# marketing routes to no lane (archive).
ROUTING = {
    "supplier_invoice":   {"extract": True,  "audit": False, "secure": False},
    "purchase_order":     {"extract": True,  "audit": False, "secure": False},
    "warranty_claim":     {"extract": True,  "audit": True,  "secure": False},
    "quality_inspection": {"extract": True,  "audit": True,  "secure": False},
    "safety_incident":    {"extract": True,  "audit": False, "secure": True},
    "hr_document":        {"extract": False, "audit": False, "secure": True},
    "shipping_manifest":  {"extract": True,  "audit": False, "secure": False},
    "marketing":          {"extract": False, "audit": False, "secure": False},
    "supplier_contract":  {"extract": False, "audit": False, "secure": False},
}

# claim_id, serial, purchase date, term months, failure date, cents, line, planted
WARRANTY_SPEC = [
    ("WC-2214", "SN-44781", date(2023, 11, 2), 24, date(2026, 3, 18), 214000, "Line 3", True),
    ("WC-2219", "SN-51209", date(2024, 9, 10), 24, date(2026, 2, 14), 68550, "Line 1", False),
    ("WC-2222", "SN-47332", date(2025, 1, 26), 18, date(2026, 4, 2), 142075, "Line 2", False),
    ("WC-2228", "SN-53867", date(2024, 12, 5), 36, date(2026, 5, 20), 31000, "Line 4", False),
    ("WC-2231", "SN-49118", date(2023, 8, 15), 24, date(2026, 1, 22), 117000, "Line 3", True),
]
CLAIM_PRODUCTS = {"WC-2214": "Servo actuator assembly", "WC-2219": "Spindle bearing cartridge",
                  "WC-2222": "Hydraulic manifold block", "WC-2228": "Line control module",
                  "WC-2231": "Drive coupling, 40 mm"}
FAILURE_NOTES = {
    "WC-2214": "Servo actuator seized at shift start; Line 3 halted 47 minutes until the spare "
               "unit was fitted.",
    "WC-2219": "Bearing noise above the acceptance limit during routine vibration check.",
    "WC-2222": "Persistent external leak at the manifold face; sealing surface out of flatness.",
    "WC-2228": "Intermittent fault codes and uncommanded stops; module swap cleared the fault.",
    "WC-2231": "Drive coupling sheared on the Line 3 infeed during normal load; no overload "
               "event on the drive log.",
}

# report id, inspection date, per-line defect rate percent (Line 3 drifts upward)
QIR_SCHEDULE = [
    ("QIR-0781", date(2026, 2, 10), {"Line 1": 0.9, "Line 2": 1.1, "Line 3": 1.2, "Line 4": 0.8}),
    ("QIR-0782", date(2026, 3, 10), {"Line 1": 0.8, "Line 2": 1.2, "Line 3": 1.9, "Line 4": 0.8}),
    ("QIR-0783", date(2026, 4, 10), {"Line 1": 0.9, "Line 2": 1.0, "Line 3": 3.1, "Line 4": 0.7}),
    ("QIR-0784", date(2026, 5, 12), {"Line 1": 0.8, "Line 2": 1.1, "Line 3": 4.8, "Line 4": 0.9}),
]
QIR_REMARKS = {
    "QIR-0781": "All lines within control limits. No action required.",
    "QIR-0782": "Line 3 defect rate above its trailing average; monitor at next audit.",
    "QIR-0783": "Line 3 reject volume elevated; infeed alignment suspected. Follow-up scheduled.",
    "QIR-0784": "Line 3 exceeds the 4.0% control limit. Escalated to process engineering.",
}

INK, GREY = colors.Color(0.106, 0.192, 0.224), colors.Color(0.42, 0.42, 0.42)
RULE, HEADBG = colors.Color(0.78, 0.78, 0.78), colors.Color(0.933, 0.925, 0.912)
WMARK = colors.Color(0.70, 0.33, 0.33, alpha=0.13)  # grey-red, semi-transparent
S_TITLE = ParagraphStyle("t", fontName="Helvetica-Bold", fontSize=15, leading=19, spaceAfter=2)
S_SUB = ParagraphStyle("s", fontName="Helvetica", fontSize=9, leading=12, textColor=GREY,
                       spaceAfter=10)
S_BODY = ParagraphStyle("b", fontName="Helvetica", fontSize=9.5, leading=13)
S_CELL = ParagraphStyle("c", fontName="Helvetica", fontSize=9, leading=11)
S_H2 = ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=10.5, leading=14, spaceAfter=4)

def _d2(cents: int) -> str:
    return f"{cents // 100}.{cents % 100:02d}"

def _usd(cents: int) -> str:
    return f"${cents // 100:,}.{cents % 100:02d}"

def _phone(rng: random.Random) -> str:
    return f"555-01{rng.randrange(100):02d}"  # canonical fictional exchange

def _email(name: str) -> str:
    return name.lower().replace(" ", ".") + "@example.com"

def _add_months(d: date, months: int) -> date:
    m = d.month - 1 + months
    y, m = d.year + m // 12, m % 12 + 1
    return date(y, m, min(d.day, calendar.monthrange(y, m)[1]))

def _invariant_canvas(*args, **kwargs) -> Canvas:
    kwargs["invariant"] = 1  # fixed CreationDate + doc ID -> byte-stable PDFs
    return Canvas(*args, **kwargs)

def _page_decorator(company: str):
    def draw(canv, _doc):
        w, h = LETTER
        canv.saveState()
        canv.setFont("Helvetica-Bold", 10)  # company name: plain text header only
        canv.setFillColor(INK)
        canv.drawString(0.75 * inch, h - 0.55 * inch, company)
        canv.setFont("Helvetica", 7.5)
        canv.setFillColor(GREY)
        canv.drawRightString(w - 0.75 * inch, h - 0.55 * inch,
                             f"Synthetic demo corpus - page {canv.getPageNumber()}")
        canv.setLineWidth(0.75)
        canv.setStrokeColor(RULE)
        canv.line(0.75 * inch, h - 0.63 * inch, w - 0.75 * inch, h - 0.63 * inch)
        # Watermark lives in the margin bands, not over the body: a giant center
        # overlay interleaves with table text when pages are machine-parsed.
        canv.setFont("Helvetica-Bold", 15)
        canv.setFillColor(WMARK)
        canv.drawCentredString(w / 2, h - 0.92 * inch, WATERMARK_TEXT)
        canv.drawCentredString(w / 2, 0.62 * inch, WATERMARK_TEXT)
        canv.restoreState()
        canv.saveState()
        canv.setFont("Helvetica-Oblique", 7.5)
        canv.setFillColor(GREY)
        canv.drawCentredString(w / 2, 0.45 * inch, FOOTER_TEXT)
        canv.restoreState()
    return draw

def _render(path: str, company: str, story: list) -> None:
    doc = SimpleDocTemplate(path, pagesize=LETTER, leftMargin=0.75 * inch,
                            rightMargin=0.75 * inch, topMargin=1.0 * inch,
                            bottomMargin=0.85 * inch, title=os.path.basename(path)[:-4],
                            author="DocFlow synthetic corpus generator")
    deco = _page_decorator(company)
    doc.build(story, onFirstPage=deco, onLaterPages=deco, canvasmaker=_invariant_canvas)

def _table(data, widths, styles, **kw) -> Table:
    t = Table(data, colWidths=widths, **kw)
    t.setStyle(TableStyle(styles + [("TOPPADDING", (0, 0), (-1, -1), 3),
                                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
    return t

def _kv(pairs) -> Table:
    rows = [[Paragraph(f"<b>{_esc(str(k))}</b>", S_CELL), Paragraph(_esc(str(v)), S_CELL)]
            for k, v in pairs]
    return _table(rows, [1.9 * inch, 4.6 * inch],
                  [("VALIGN", (0, 0), (-1, -1), "TOP"),
                   ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.Color(0.87, 0.87, 0.87))])

def _grid(header, rows, widths) -> Table:
    return _table([header] + rows, widths,
                  [("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 8.5),
                   ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
                   ("BACKGROUND", (0, 0), (-1, 0), HEADBG),
                   ("GRID", (0, 0), (-1, -1), 0.4, RULE),
                   ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                   ("VALIGN", (0, 0), (-1, -1), "TOP")], repeatRows=1)

def _items_grid(items) -> Table:
    return _grid(["Description", "Qty", "Unit price", "Amount"],
                 [[Paragraph(_esc(d), S_CELL), str(q), _usd(p), _usd(q * p)] for d, q, p in items],
                 [3.9 * inch, 0.7 * inch, 1.2 * inch, 1.2 * inch])

def _totals(rows) -> Table:
    return _table([[label, _usd(c)] for label, c in rows], [1.7 * inch, 1.3 * inch],
                  [("FONT", (0, 0), (-1, -1), "Helvetica", 9),
                   ("FONT", (0, -1), (-1, -1), "Helvetica-Bold", 9.5),
                   ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                   ("LINEABOVE", (0, -1), (-1, -1), 0.8, INK)], hAlign="RIGHT")

def _items_gt(items):
    return [{"description": d, "qty": q, "unit_price": _d2(p), "amount": _d2(q * p)}
            for d, q, p in items]

def _form(title, subtitle, pairs, *tail):
    """Story skeleton shared by every form-style document."""
    return [Paragraph(title, S_TITLE), Paragraph(subtitle, S_SUB), _kv(pairs), *tail]

def _sec(heading, body):
    return [Spacer(0, 10), Paragraph(heading, S_H2), Paragraph(_esc(body), S_BODY)]

def _invoice(inv_id, company, vendor, inv_date, items, contact, phone, planted):
    subtotal = sum(q * p for _, q, p in items)
    tax = (subtotal * 825 + 5000) // 10000  # 8.25 percent, half-up, exact cents
    total, due = subtotal + tax, inv_date + timedelta(days=30)
    story = _form("INVOICE", f"{_esc(vendor)} - {_esc(VENDORS[vendor])}",
                  [("Invoice number", inv_id), ("Invoice date", inv_date.isoformat()),
                   ("Payment due", due.isoformat()), ("Terms", "Net 30"),
                   ("Bill to", f"{company}, Receiving Dept, {FICTIONAL_SITE}"),
                   ("Vendor contact", f"{contact} - {_email(contact)} - {phone}")],
                  Spacer(0, 14), _items_grid(items), Spacer(0, 8),
                  _totals([("Subtotal", subtotal), ("Tax (8.25%)", tax), ("Total due", total)]))
    gt = {"invoice_number": inv_id, "vendor": vendor, "invoice_date": inv_date.isoformat(),
          "due_date": due.isoformat(), "subtotal": _d2(subtotal), "tax": _d2(tax),
          "total": _d2(total), "line_items": _items_gt(items),
          "serial_numbers": sorted({s for d, _, _ in items for s in re.findall(r"SN-\d+", d)})}
    return inv_id, story, gt, planted

def _build_invoices(company, rng):
    planted_items = [("Servo actuator assembly, serial SN-44781", 1, 198000),
                     ("Actuator mounting bracket kit", 2, 4550),
                     ("On-site commissioning service, 1 day", 1, 35000)]
    docs = [_invoice("INV-88213", company, "Miller Tooling LLC", date(2023, 11, 2),
                     planted_items, rng.choice(PEOPLE), _phone(rng), True)]
    for i in range(4):
        vendor = rng.choice(VENDOR_NAMES)
        inv_date = date(2026, 4, 6) + timedelta(days=rng.randrange(70))
        items = [(d, rng.randint(1, 12), p) for d, p in rng.sample(PARTS, rng.randint(3, 5))]
        docs.append(_invoice(f"INV-{88214 + i}", company, vendor, inv_date, items,
                             rng.choice(PEOPLE), _phone(rng), False))
    return docs

def _build_pos(company, rng):
    docs = []
    for i, po_id in enumerate(["PO-3341", "PO-3342"]):
        vendor, od = VENDOR_NAMES[i % 3], date(2026, 3, 9) + timedelta(days=rng.randrange(80))
        need, buyer = od + timedelta(days=21), rng.choice(PEOPLE)
        items = [(d, rng.randint(2, 20), p) for d, p in rng.sample(PARTS, rng.randint(3, 4))]
        total = sum(q * p for _, q, p in items)
        story = _form("PURCHASE ORDER", f"{_esc(company)} - Procurement",
                      [("PO number", po_id), ("Order date", od.isoformat()),
                       ("Need-by date", need.isoformat()),
                       ("Vendor", f"{vendor}, {VENDORS[vendor]}"),
                       ("Ship to", f"{company}, {FICTIONAL_SITE}"),
                       ("Buyer", f"{buyer} - {_email(buyer)} - {_phone(rng)}")],
                      Spacer(0, 14), _items_grid(items), Spacer(0, 8),
                      _totals([("PO total", total)]))
        gt = {"po_number": po_id, "vendor": vendor, "order_date": od.isoformat(),
              "need_by_date": need.isoformat(), "total": _d2(total),
              "line_items": _items_gt(items)}
        docs.append((po_id, story, gt, False))
    return docs

def _build_claims(company, rng):
    docs = []
    for cid, serial, purchased, term, failed, cents, line, planted in WARRANTY_SPEC:
        expires, contact = _add_months(purchased, term), rng.choice(PEOPLE)
        proof = "Invoice INV-88213, Miller Tooling LLC" if cid == "WC-2214" else "On file"
        story = (_form("WARRANTY CLAIM FORM",
                       f"Supplier warranty recovery claim submitted by {_esc(company)}",
                       [("Claim ID", cid), ("Claimant", f"{company}, {FICTIONAL_SITE}"),
                        ("Component", CLAIM_PRODUCTS[cid]), ("Serial number", serial),
                        ("Purchase date", purchased.isoformat()), ("Warranty term", f"{term} months"),
                        ("Failure date", failed.isoformat()), ("Claim amount", _usd(cents)),
                        ("Production line", line), ("Proof of purchase", proof),
                        ("Filed by", f"{contact} - {_email(contact)} - {_phone(rng)}")])
                 + _sec("Failure description", FAILURE_NOTES[cid])
                 + _sec("Requested resolution",
                        "Credit or replacement under the supplier warranty terms."))
        gt = {"claim_id": cid, "serial_number": serial, "component": CLAIM_PRODUCTS[cid],
              "purchase_date": purchased.isoformat(), "warranty_term_months": term,
              "failure_date": failed.isoformat(), "warranty_expires": expires.isoformat(),
              "within_warranty": failed <= expires, "claim_amount": _d2(cents),
              "production_line": line,
              "proof_of_purchase": "INV-88213" if cid == "WC-2214" else None}
        docs.append((cid, story, gt, planted))
    return docs

def _build_qirs(company, rng):
    docs, shifts = [], ["First shift", "Second shift", "First shift", "First shift"]
    for i, (qid, d, rates) in enumerate(QIR_SCHEDULE):
        inspector, rows, gt_rows, tu, td = rng.choice(PEOPLE), [], [], 0, 0
        for line, rate in rates.items():
            units = rng.choice([1000, 2000, 3000])
            defects = int(round(rate * units / 100))  # rates chosen so this is exact
            tu, td = tu + units, td + defects
            rows.append([line, f"{units:,}", str(defects), f"{rate:.1f}%"])
            gt_rows.append({"line": line, "units_inspected": units, "defects": defects,
                            "defect_rate_pct": rate})
        rows.append(["All lines", f"{tu:,}", str(td), f"{td / tu * 100:.2f}%"])
        story = (_form("QUALITY INSPECTION REPORT",
                       f"Final assembly audit - {_esc(company)}, {FICTIONAL_SITE}",
                       [("Report ID", qid), ("Inspection date", d.isoformat()),
                        ("Shift", shifts[i]), ("Inspector", f"{inspector} - {_email(inspector)}"),
                        ("Method", "AQL sampling per QP-104, visual + gauge")],
                       Spacer(0, 14),
                       _grid(["Production line", "Units inspected", "Defects", "Defect rate"],
                             rows, [1.9 * inch, 1.8 * inch, 1.5 * inch, 1.8 * inch]))
                 + _sec("Inspector remarks", QIR_REMARKS[qid]))
        gt = {"report_id": qid, "inspection_date": d.isoformat(), "inspector": inspector,
              "lines": gt_rows, "line3_defect_rate_pct": rates["Line 3"]}
        docs.append((qid, story, gt, True))
    return docs

def _build_incidents(company, rng):
    specs = [("SI-0112", date(2026, 4, 21), "09:40", "Line 3 guarding, west end",
              "Maintenance Mechanic",
              "While adjusting the Line 3 infeed guard, the employee pinched the left index "
              "finger between the guard frame and its bracket. First aid on site; returned same shift.",
              "Guard adjustment procedure updated; two-person rule reinforced for guard work."),
             ("SI-0113", date(2026, 5, 30), "14:15", "Receiving dock, bay 2", "Material Handler",
              "Employee slipped on hydraulic fluid residue near bay 2 while staging inbound "
              "pallets. Minor bruising only; area cordoned and cleaned.",
              "Spill kit restocked at the dock; anti-slip floor coating scheduled.")]
    docs = []
    for sid, d, t, area, role, narrative, action in specs:
        employee, reporter = rng.sample(PEOPLE, 2)
        story = (_form("SAFETY INCIDENT REPORT", f"Internal EHS record - {_esc(company)}",
                       [("Incident ID", sid), ("Date", d.isoformat()), ("Time", t),
                        ("Site", FICTIONAL_SITE), ("Area", area), ("Employee", f"{employee} ({role})"),
                        ("Reported by", f"{reporter} - {_email(reporter)} - {_phone(rng)}"),
                        ("Injury classification", "First aid only"), ("OSHA recordable", "No"),
                        ("Days away from work", "0")])
                 + _sec("What happened", narrative) + _sec("Corrective action", action))
        gt = {"incident_id": sid, "incident_date": d.isoformat(), "site": FICTIONAL_SITE,
              "area": area, "employee": employee, "severity": "First aid only",
              "osha_recordable": False}
        docs.append((sid, story, gt, False))
    return docs

def _build_hr(company, rng):
    employee, approver = "Dana Whitfield", rng.choice(PEOPLE[1:])
    story = (_form("EMPLOYEE STATUS CHANGE NOTICE",
                   f"Human Resources - {_esc(company)} - CONFIDENTIAL",
                   [("Document ID", "HR-0007"), ("Employee", employee),
                    ("Employee ID", "EMP-0042"), ("SSN", FAKE_SSN),
                    ("Contact", f"{_email(employee)} - {_phone(rng)}"),
                    ("Work site", FICTIONAL_SITE), ("Effective date", "2026-04-01"),
                    ("Change", "Promotion"), ("From title", "Quality Technician II"),
                    ("To title", "Senior Quality Technician"), ("New annual salary", "$68,400.00"),
                    ("Approved by", approver)])
             + _sec("Notes", "Promotion recognizes sustained inspection accuracy and audit "
                             "leadership. Payroll change effective with the April cycle."))
    gt = {"document_id": "HR-0007", "document_type": "Employee status change",
          "employee": employee, "ssn": FAKE_SSN, "effective_date": "2026-04-01",
          "new_title": "Senior Quality Technician"}
    return [("HR-0007", story, gt, False)]

def _build_manifests(company, rng):
    docs = []
    for i, (mid, ship) in enumerate([("SM-0451", date(2026, 5, 14)),
                                     ("SM-0452", date(2026, 6, 5))]):
        carrier, dest = rng.choice(CARRIERS), DESTINATIONS[i]
        rows, gt_rows, tc, tw = [], [], 0, 0
        for j, (desc, _) in enumerate(rng.sample(PARTS, rng.randint(3, 4))):
            pkg, cartons, wt = f"{mid}-P{j + 1:02d}", rng.randint(1, 10), rng.randint(60, 400)
            tc, tw = tc + cartons, tw + wt
            rows.append([pkg, Paragraph(_esc(desc), S_CELL), str(cartons), f"{wt} lb"])
            gt_rows.append({"package_id": pkg, "contents": desc, "cartons": cartons,
                            "weight_lb": wt})
        rows.append(["Total", "", str(tc), f"{tw} lb"])
        seal = f"TRL-{rng.randrange(1000, 9999)} / SEAL-{rng.randrange(10000, 99999)}"
        story = _form("SHIPPING MANIFEST", f"Outbound freight - {_esc(company)}",
                      [("Manifest ID", mid), ("Ship date", ship.isoformat()),
                       ("Carrier", carrier), ("Origin", f"{company}, {FICTIONAL_SITE}"),
                       ("Destination", dest), ("Trailer / seal", seal)],
                      Spacer(0, 14),
                      _grid(["Package", Paragraph("<b>Contents</b>", S_CELL), "Cartons", "Weight"],
                            rows, [1.3 * inch, 3.6 * inch, 0.9 * inch, 1.2 * inch]))
        gt = {"manifest_id": mid, "ship_date": ship.isoformat(), "carrier": carrier,
              "origin": FICTIONAL_SITE, "destination": dest, "package_count": len(gt_rows),
              "total_cartons": tc, "total_weight_lb": tw, "packages": gt_rows}
        docs.append((mid, story, gt, False))
    return docs

def _build_marketing(company, rng):
    del company, rng  # junk mail is vendor-authored; nothing random needed
    story = [Paragraph("SPRING 2026 ALLOY STOCK CATALOG", S_TITLE),
             Paragraph("Vexler Steel Co - 88 Ingot Ave, Demoville", S_SUB),
             Paragraph("New season, sharper prices on the alloys your floor runs on. Vexler "
                       "Steel now stocks over 400 certified grades, same-week delivery.", S_BODY),
             Spacer(0, 8),
             Paragraph("- 4140 and 4340 pre-hardened bar, cut to length<br/>- Stainless plate "
                       "304/316 with mill certs<br/>- Volume pricing on orders over 5 tons", S_BODY),
             Spacer(0, 10), Paragraph("Request the catalog: sales@example.com - 555-0100 - "
                                      "www.example.com/vexler-catalog", S_BODY)]
    gt = {"title": "Spring 2026 Alloy Stock Catalog", "sender": "Vexler Steel Co",
          "contact_email": "sales@example.com"}
    return [("MKT-001", story, gt, False)]

def _build_contracts(company, rng):
    del rng  # contract terms are the story; nothing random belongs in them
    c = _esc(company)
    msa = [Paragraph("MASTER SUPPLY AGREEMENT", S_TITLE),
           Paragraph(f"CT-7701 - between {c} (Buyer) and Miller Tooling LLC (Supplier) - "
                     f"effective 1 March 2024", S_SUB),
           Spacer(0, 8),
           Paragraph("1. Scope", S_H2),
           Paragraph("Supplier will manufacture and deliver the components listed in each "
                     "purchase order issued under this agreement. Each purchase order "
                     "references these terms unless it states otherwise in writing.", S_BODY),
           Spacer(0, 6),
           Paragraph("2. Delivery and late-delivery penalty", S_H2),
           Paragraph("Time is of the essence. Where delivery arrives after the need-by date "
                     "on the purchase order, Buyer may deduct a late-delivery penalty of five "
                     "percent (5%) of the purchase order value for each full week of delay, "
                     "capped at fifteen percent (15%) in aggregate. Penalties are deducted "
                     "from the next invoice, not invoiced separately.", S_BODY),
           Spacer(0, 6),
           Paragraph("3. Component warranty pass-through", S_H2),
           Paragraph("Supplier warrants all delivered components for twenty-four (24) months "
                     "from delivery. Where Buyer honours an end-customer warranty claim "
                     "caused by a defective supplied component, Supplier reimburses Buyer "
                     "the component cost plus documented labour, provided the claim is "
                     "notified within sixty (60) days of Buyer settling it.", S_BODY),
           Spacer(0, 6),
           Paragraph("4. Termination", S_H2),
           Paragraph("Either party may terminate on ninety (90) days written notice. "
                     "Purchase orders accepted before notice survive termination.", S_BODY),
           Spacer(0, 6),
           Paragraph("5. Governing terms", S_H2),
           Paragraph("This agreement is governed by the laws of the State of Demoland. "
                     "It is fictional demonstration material and binds nobody.", S_BODY)]
    gt_msa = {"contract_id": "CT-7701", "supplier": "Miller Tooling LLC",
              "late_delivery_penalty": "5% per full week, capped at 15%",
              "component_warranty_months": "24"}
    pol = [Paragraph("WARRANTY TERMS AND SERVICE POLICY", S_TITLE),
           Paragraph(f"CT-7702 - {c} - customer-facing policy - revision C, "
                     f"January 2025", S_SUB),
           Spacer(0, 8),
           Paragraph("1. Coverage window", S_H2),
           Paragraph(f"{c} warrants each unit against defects in materials and workmanship "
                     "for the warranty term stated on the unit's certificate, measured from "
                     "the date of purchase. Coverage ends when that term lapses; failures "
                     "reported after the coverage window are not eligible for repair or "
                     "replacement at company cost, and are quoted as billable service.", S_BODY),
           Spacer(0, 6),
           Paragraph("2. Filing a claim", S_H2),
           Paragraph("Claims must be filed within thirty (30) days of the failure date, with "
                     "the unit serial number, purchase date and a description of the failure "
                     "mode. Claims missing a verifiable purchase date are held for review "
                     "rather than denied outright.", S_BODY),
           Spacer(0, 6),
           Paragraph("3. Exclusions", S_H2),
           Paragraph("Damage from improper installation, unauthorised modification, or "
                     "operation outside the published duty cycle is excluded. Consequential "
                     "and incidental damages are excluded to the extent law allows.", S_BODY),
           Spacer(0, 6),
           Paragraph("4. Out-of-window goodwill", S_H2),
           Paragraph("Requests outside the coverage window may be considered for partial "
                     "goodwill credit where the failure mode matches an open quality "
                     "investigation. Goodwill is discretionary and never an admission "
                     "of liability.", S_BODY)]
    gt_pol = {"contract_id": "CT-7702", "policy": "Warranty Terms and Service Policy",
              "claim_filing_deadline_days": "30"}
    return [("CT-7701", msa, gt_msa, False), ("CT-7702", pol, gt_pol, False)]

def generate_corpus(company: str, out_dir: str, seed: int = 38) -> dict:
    """Generate the 24-document corpus into out_dir and return the manifest:
    {"company", "seed", "generated": [{doc_id, type, filename, planted_trap,
    ground_truth}]} -- ground_truth carries the exact field values the
    certification gate verifies extraction against. Also written to
    {out_dir}/manifest.json."""
    rng = random.Random(seed)
    os.makedirs(out_dir, exist_ok=True)
    builders = (_build_invoices, _build_pos, _build_claims, _build_qirs,
                _build_incidents, _build_hr, _build_manifests, _build_marketing,
                _build_contracts)
    generated = []
    for dtype, build in zip(TAXONOMY, builders):  # TAXONOMY declaration order
        for doc_id, story, gt, planted in build(company, rng):
            filename = f"{doc_id}.pdf"
            _render(os.path.join(out_dir, filename), company, story)
            generated.append({"doc_id": doc_id, "type": dtype, "filename": filename,
                              "planted_trap": planted, "ground_truth": gt})
    counts = {t: sum(1 for e in generated if e["type"] == t) for t in TAXONOMY}
    if len(generated) != 24 or any(counts[t] != TAXONOMY[t]["count"] for t in TAXONOMY):
        raise RuntimeError(f"corpus shape mismatch: {counts}")
    manifest = {"company": company, "seed": seed, "generated": generated}
    with open(os.path.join(out_dir, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2)
    return manifest

if __name__ == "__main__":
    import sys
    _company = sys.argv[1] if len(sys.argv) > 1 else "Acme Manufacturing"
    _dest = sys.argv[2] if len(sys.argv) > 2 else "./corpus_out"
    print(f"wrote {len(generate_corpus(_company, _dest)['generated'])} documents to {_dest}")
